global:
  qsname: quickstart-magento
  reporting: true
  cis3bucket:  s3://quickstart-ci-bucket
  regions:
    - us-east-1
 
tests:
  magento:
    template_file: Magento-Quickstart-NewVPC.template
    parameter_input: quickstart-magento.json
