global:
  qsname: quickstart-magento
  reporting: true
  regions:
    - us-east-1
    - us-west-1
    - eu-west-1
    - us-west-2
    - sa-east-1
    - eu-central-1
    - ap-northeast-1
    - ap-southeast-1
    - ap-southeast-2
    - ap-northeast-2
  cis3bucket:  s3://quickstart-ci-bucket
 
tests:
  quickstart-magentot1:
    template_file: quickstart-magento-example1.template
    parameter_input: quickstart-magento-exampleparms1.json
  quickstart-magentot2:
    template_file: quickstart-magento-example2.template
    parameter_input: quickstart-magento-exampleparms2.json
