global:
  qsname: quickstart-magento
  owner: sshvans@amazon.com
  regions:
    - eu-west-1
    - us-east-1
    - us-east-2
    - us-west-2
  reporting: true

tests:
  quickstart-magentot1:
    parameter_input: quickstart-magento.json
    template_file: quickstart-magento-newVPC.template
